### ISSUE TITLE
Can't use module relying on jar code after 5.0.0 migration

### ISSUE THREAD

**Issue by gmella** [eXist-db/exist#3004]
### What is the problem
The installation of some modules coming with jar/java code inside are not working. 
I notived that on one module which we developed and see after some test that it also occurs on expath `ft-client`

Error shown is `exerr:ERROR error found while loading module ft-client: Unable to instantiate module from EXPathrepository: org.expath.exist.ftclient.ExistExpathFTClientModule`
I can provide more log but reproducer is quite easy.

### What did you expect
Get common distributed modules and my mvn module (freshly compiled with exist-core 5.0.0 dependency ) back again.

### Describe how to reproduce or add a test
install step:
```
xquery version "3.1";
repo:install-and-deploy("http://expath.org/ns/ft-client", "1.1.6", "http://demo.exist-db.org/exist/apps/public-repo/modules/find.xql")
```
use step:

```
xquery version "3.1";
import module namespace ft-client="http://expath.org/ns/ft-client";
ft-client:connect(xs:anyURI('ftp://ftp.de.debian.org/debian/'))
```

### Context information

eXist Version: | 5.1.0-SNAPSHOT
eXist Build: | 20190904093321
Operating System: | Linux 4.9.0-8-amd64 amd64
Java Version: | 1.8.0_222

I also tried with Docker versions latest, 5.0.0 and 4.7.1 and a more classical one with 5.0.0 installer. Was ok only on 4.7.1 and previous.

I changed `conf.xml` but that is not relevant for this issue.
let me share how in my docker-compose
```
oival:
  image: existdb/existdb:5.0.0
  ports:
    - "8080:8080"
  volumes:
    - ./jmmc-resources/build/jmmc-resources-0.23.xar:/exist/autodeploy/jmmc-ressources.xar
    - ./oival/build/oival-2.9.xar:/exist/autodeploy/oival.xar
    # overwrite conf.xml for output-size-limit="10000000" and enable-java-binding="yes"
    - ./docker/exist/conf.xml:/exist/etc/conf.xml
  user: 0:1000
  restart: always
```

and address a very big Thank you for all of your work!
