### ISSUE TITLE
[Feature] Docker: make Healthcheck cmd unaffected by admin pw changes 

### ISSUE THREAD

**Issue by ambs** [eXist-db/exist#3165]
The command used to check the container health doesn't use any authentication. Probably either exist should allow to query the running version without authentication, or the health check command should use authentication.

I can give more detail, or test any solution you might suggest.

**Comment by duncdrum** [comment]
Please fill in the template, we need to know exist, docker, and os versions. 

This seems WAI to me, i don't quite understand yet what we would gain by switching to an authenticated command string? It would break for every production image that modifies authentication realms, just as it does now. You can provide a modified `HEALTHCHECK` in your own docker or docker-compose files. Which will replace the one provided in the base image.

**Comment by ambs** [comment]
eXist version 5.2.0-SNAPSHOT, running on Docker version 19.03.5, build 633a0ea838.
Running on Debian 10.2.

Docker-compose:
``````
version: '2'
services:
  exist:
    build: ./dacl/docker
    mem_limit: 2000m
    container_name: exist
    ports:
        - 8080:8080
        - 8443:8443
    volumes:
        - ./data:/exist/data
        - ./config:/exist/config
        - ./dacl:/import
        - ./outdir:/export
`````

Still not sure what should be the solution. But either we need to find a health check code that is useful, or better to remove it. Will try to help finding a good alternative.
