### ISSUE TITLE
[BUG] Docker : Unable to access jarfile start.jar while running single stage image proposed on DockerHub

### ISSUE THREAD

**Issue by LaurentNoyon** [eXist-db/exist#3925]
**Describe the bug**

I'm trying to install eXistDB with docker. I'm willing to set the admin password during the installation so I chose to follow the example of "A slightly more complex single stage image" available on dockerhub : https://hub.docker.com/r/existdb/existdb

Here is my Dockerfile :
```
FROM existdb/existdb
RUN ["java", "-jar", "start.jar", "client", "--no-gui", "-l", "-u", "admin", "-P", "", "-x", "sm:passwd('admin','123')"]
ADD https://github.com/eXist-db/documentation/releases/download/4.0.4/exist-documentation-4.0.4.xar /exist/autodeploy
```
While running it, I get the following error : 
```
Building exist
Step 1/3 : FROM existdb/existdb
 ---> 764e86042d78
Step 2/3 : RUN ["java", "-jar", "start.jar", "client", "--no-gui", "-l", "-u", "admin", "-P", "", "-x", "sm:passwd('admin','123')"]
 ---> Running in c2600d262abb
Error: Unable to access jarfile start.jar
```

**Context**
- Ubuntu 20.04.2 LTS
- The Dockerfile is read in a docker-compose.yml, here is a sample :
```
version: '3.7'

services:
    exist:
        build:
            context: ./exist/
        ports:
            - "8083:8080"
            - "8084:8443"
        networks:
          - exist_network
        volumes:
          - type: volume
            source: exist-data
            target: /usr/exist/data
          - type: volume
            source: exist-config
            target: /usr/exist/config
        restart: always 

volumes:
    exist-data:
        driver: local
        name: exist-data
    exist-config:
        driver: local
        name: exist-config

networks:
  exist_network:
    driver: bridge
```
The installation of exist works fine when using built in image instead of Dockerfile
