### ISSUE TITLE
[DOCKER EXIST PASSWORD] Cannot manage to change password using ARG in Dockerfile

### ISSUE THREAD

**Issue by LaurentNoyon** [eXist-db/exist#3984]
A year ago, @eduarddrenth posted #2957 to find a way to use an argument to pass the exist admin password to the Dockerfile. It didn't seems to work and it's not working still. I would like to avoid using extra systems like Buildkit. Could you tell me if there was an update about how to do that ? I tried using environment variables, argument + environment variable, argument only etc ... Couldn't find any solution.

With mysql image, it's possible to give those arguments directly from the docker-compose.yml, like so : 
```
environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "password123"
            MYSQL_USER: "myusername"
            MYSQL_PASSWORD: "password456"
            MYSQL_DATABASE: "mydatabase"
```
Wouldn't it be possible with exist ?

Thanks in advance for your help.
